server:
  port: 18081

spring:
  zipkin:
    base-url: http://localhost:9411/
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: create
  datasource:
    platform: postgres
    url: jdbc:postgresql://localhost:5432/sampledb
    username: root
    password: root
    driver-class-name: org.postgresql.Driver
  application:
    name: payment-service

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance: localhost

management:
  endpoint:
    shutdown:
      enable: true
  endpoints:
    web:
      exposure:
        include:
          - '*'