server:
  port: 18080

spring:
  zipkin:
    base-url: http://localhost:9411/
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
  application:
    name: order-service


eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance: localhost

management:
  endpoint:
    shutdown:
      enable: true
  endpoints:
    web:
      exposure:
        include:
          - '*'